<div class="wrapper style2">
    <section id="main" class="container">
        <header class="major">
            <h2>About</h2>
            <p>Short story on cron and the motivation behind CronKeep</p>
        </header>

        <section>
            <span class="image fit"><img src="images/typewriter.jpg" alt="short story illustration"></span>
            <p>Perhaps you're familiar with Windows' Task Scheduler. One could use it to schedule software to run automatically at predetermined hours. Say one wants to have their favorite music player launched every day, in the morning. Cron tasks are the same thing, but for Linux. Probably most Linux distributions ship with a visual tool that lets people schedule tasks just like you would on Windows.</p>

            <p>But on a Linux <i>server</i>, you're stuck to adding cron jobs by hand in a text editor in a black screen. They look something like <code>*/15 9-17 * * 1-5 /do/my/backup</code>, of which <code>*/15 9-17 * * 1-5</code> means the command would run automatically every 15 minutes, from 9 to 5, on weekdays. I found that people struggle with introducing time like that - I did too in the past.</p>

            <p>People use cron jobs on their servers to schedule automatic backups, run various data integrations with external vendors, generate large batches of images, run newsletters and whatnot. Still in some organizations, the people who manage the cron jobs are the system administrators, which often are the only ones with the right kind of security access to do so. And they're usually not comfortable letting developers or other people in.</p>

            <p>CronKeep is an attempt to solve these problems:</p>

            <ul>
                <li>give teams visibility to the existing cron jobs;</li>
                <li>allow team members to add cron jobs, without the special shell access that sysadmins have - they can do it from their browser;</li>
                <li>developers and other members of the team can run the tasks manually if they need to, and not have to buzz the guys with server access every time;</li>
                <li>users can use friendly UI to add cron jobs (like you'd schedule a calendar meeting) - they no longer have to fiddle with stuff like <code>*/15 9-17 * * 1-5</code>.</li>
            </ul>
            
            <p>I worked on projects with a few dozens automatic tasks scheduled, and I used to be one of the guys that people bugged with running cron jobs off hours :). This is how I got the idea for CronKeep. It's open source and available for free for all kinds of organizations.</p>
            <p>— <i><b>Bogdan Ghervan</b>, Lead Developer</i></p>
        </section>

    </section>
</div>