<section id="demo" class="wrapper style1">
    <div class="container">
        <span class="device fit"><iframe src="http://demo.cronkeep.com"></iframe></span>
    </div>
</section>

<section class="wrapper style4 special">
    <div class="container">
        Please note that while CronKeep allows running cron jobs on demand, this capability is intentionally
        disabled in the demo app.
    </div>
</section>
