<section id="intro" class="wrapper style1">
    <div class="container">
        <div class="inner">
            <header class="major">
                <h2>The Human-Friendly<br />
                Crontab Manager</h2>
            </header>
            <p>
                CronKeep enables teams to have visibility over what cron jobs are scheduled, run jobs on demand
                or add new cron jobs in a human-friendly way without the need for sysadmin-level access.
            </p>
            <ul class="actions">
                <li><a href="https://github.com/cronkeep/cronkeep#installation" class="button icon fa-cloud-download">Get it now</a></li>
            </ul>
        </div><a href="/demo" title="Click for Live Demo"><span class="device image fit"><img src="images/job-list.png" alt="CronKeep screenshot"></span></a>
    </div>
</section>
    
<section id="social" class="wrapper style3">
    <span class="facebook-share">
        <div class="fb-share-button" data-href="http://www.cronkeep.com" data-layout="button" data-mobile-iframe="true"></div>
    </span>
    <span class="twitter-share">
        <a href="https://twitter.com/share" class="twitter-share-button" data-url="http://www.cronkeep.com"
           data-related="bogdanghervan" data-text="CronKeep: The open-source human-friendly crontab manager"
           data-via="CronKeep" data-hashtags="cronkeep" data-count="none">Tweet</a>
    </span>
    <span class="github-star">
        <iframe src="http://ghbtns.com/github-btn.html?user=cronkeep&repo=cronkeep&type=watch&count=true"
                width="90" height="20" frameborder="0" scrolling="0" allowTransparency="true"></iframe>
    </span>
</section>
    
<section class="wrapper style2">
    <div class="container">
        <div class="row">
            <div class="6u 12u$(2)">
                <section class="feature">
                    <i class="icon fa-flag-checkered"></i>
                    <h3>Run Jobs On Demand</h3>
                    <p>
                        Run cron jobs outside scheduled hours at a click's distance, without having to tinker
                        with the command line.
                    </p>
                </section>
            </div>
            <div class="6u$ 12u$(2)">
                <section class="feature">
                    <i class="icon fa-clock-o"></i>
                    <h3>Friendly Time Keeping</h3>
                    <p>Cron jobs can be added like you were adding an entry in your calendar, using a set of options that is common to most schedules.</p>
                </section>
            </div>
            <div class="6u 12u$(2)">
                <section class="feature">
                    <i class="icon fa-pause"></i>
                    <h3>Pause Cron Schedules</h3>
                    <p>You can pause cron jobs from ever going off, and resume them anytime.</p>
                </section>
            </div>
            <div class="6u$ 12u$(2)">
                <section class="feature">
                    <i class="icon fa-github"></i>
                    <h3>Open Source</h3>
                    <p>
                        CronKeep is a free to use application, both for non-profit and commercial organizations,
                        released under the terms of Apache License 2.0.
                    </p>
                </section>
            </div>
            <div class="6u 12u$(2)">
                <section class="feature">
                    <i class="icon fa-magic"></i>
                    <h3>Easy to Setup</h3>
                    <p>CronKeep is designed to require the minimum to function, just drop it in and it works on most systems.</p>
                </section>
            </div>
            <div class="6u$ 12u$(2)">
                <section class="feature">
                    <i class="icon fa-tablet"></i>
                    <h3>Responsive Design</h3>
                    <p>CronKeep looks good on any device size, so that you could effortlessly manage your cron tasks remotely.</p>
                </section>
            </div>
        </div>
    </div>
</section>
