<footer id="footer">
    <ul class="icons">
        <li>
            <a href="https://github.com/cronkeep/cronkeep" class="icon fa-github"><span class="label">GitHub</span></a>
        </li>
        <li>
            <a href="https://twitter.com/cronkeep" class="icon fa-twitter"><span class="label">Twitter</span></a>
        </li>
        <li>
            <a href="mailto:hello@cronkeep.com" class="icon fa-envelope"><span class="label">Email</span></a>
        </li>
    </ul>
    <div class="copyright">
        &copy; CronKeep. Licensed under
        <a href="/license">Apache License 2.0</a>.
    </div>
    <p>
        <a href="https://github.com/cronkeep/cronkeep/issues">Issues</a> on GitHub
        · For any inquiries, <a href="mailto:hello@cronkeep.com">hello@cronkeep.com</a>.
    </p>
</footer>
